apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-electricaa
spec:
  replicas: 3  # Number of pods to run
  selector:
    matchLabels:
      app: django_electricaa
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-electricaa-container
        image: juvobest/electrical_project:latest  # Replace with your built image
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /code
          name: code-volume
        env:
        - name: DEBUG
          value: "True"
      volumes:
      - name: code-volume
        hostPath:
          path: /mnt/c:uchepython/myproject
